const calls=[]; globalThis.fetch=async(url,o)=>{calls.push({url,body:JSON.parse(o.body),headers:o.headers}); return {ok:true,json:async()=>({id:'x'})};};
const app={log:{info(){},error(){},warn(){}}};
let P=0,F=0; const t=(n,c,x)=>{c?P++:(F++,console.log('  FAIL '+n+(x?' -- '+x:'')))};
process.env.NODE_ENV='production';
let m=await import('../src/notify.js');
t('1 no config → console, honest', (await m.sendEmail(app,{to:'a@b.com',subject:'s',code:'123456'})).sent===false);
process.env.SMTP_HOST='smtp.gmail.com'; process.env.SMTP_USER='x@gmail.com'; process.env.SMTP_PASS='abcd efgh';
t('2 SMTP only → smtp', m.emailTransport()==='smtp');
process.env.BREVO_API_KEY='bk'; t('3 Brevo beats SMTP', m.emailTransport()==='brevo');
process.env.RESEND_API_KEY='rk'; process.env.EMAIL_FROM='ParentFirst <hello@parentfirst.app>';
t('4 Resend beats all', m.emailTransport()==='resend');
const r=await m.sendEmail(app,{to:'dada@x.com',subject:'482913 is your ParentFirst code',heading:'Confirm your email',code:'482913',lines:['Enter this code.']});
t('5 sent via resend', r.sent && r.via==='resend');
const c=calls.at(-1);
t('6 hits api.resend.com over HTTPS', c.url==='https://api.resend.com/emails' && c.headers.Authorization==='Bearer rk');
t('7 from/to/subject correct', c.body.from==='ParentFirst <hello@parentfirst.app>' && c.body.to[0]==='dada@x.com' && /482913/.test(c.body.subject));
t('8 code in big box in html', /letter-spacing:10px[^>]*>482913</.test(c.body.html));
t('9 plain-text alternative', /Code: 482913/.test(c.body.text));
delete process.env.RESEND_API_KEY;
await m.sendEmail(app,{to:'dada@x.com',subject:'s',lines:['hi']});
t('10 brevo payload shape', calls.at(-1).url.includes('brevo') && calls.at(-1).body.sender.email==='hello@parentfirst.app' && calls.at(-1).headers['api-key']==='bk');
globalThis.fetch=async()=>({ok:false,status:403,text:async()=>'domain not verified'});
const bad=await m.sendEmail(app,{to:'x@y.com',subject:'s'});
t('11 API error reported honestly, no throw', bad.sent===false && /403/.test(bad.reason));
console.log('MAILER: '+P+' passed, '+F+' failed');
